#!/usr/bin/env python3
"""Regenerate knowledge-graph/README.md from entities.jsonl and relationships.jsonl."""

import json
from collections import defaultdict
from pathlib import Path

KG_DIR = Path.home() / ".claude" / "knowledge-graph"


def load_jsonl(path):
    items = []
    if not path.exists():
        return items
    with open(path) as f:
        for line in f:
            if line.strip():
                try:
                    items.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return items


def dedupe(entities):
    seen = {}
    for e in entities:
        key = (e.get("name", "").lower(), e.get("type", ""))
        if key not in seen or len(e.get("description", "")) > len(seen[key].get("description", "")):
            seen[key] = e
    return list(seen.values())


def main():
    entities = dedupe(load_jsonl(KG_DIR / "entities.jsonl"))
    rels = load_jsonl(KG_DIR / "relationships.jsonl")

    by_type = defaultdict(list)
    for e in entities:
        by_type[e.get("type", "unknown")].append(e)

    rel_by_type = defaultdict(list)
    for r in rels:
        rel_by_type[r.get("type", "unknown")].append(r)

    lines = []
    lines.append("# Knowledge Graph")
    lines.append("")
    lines.append("Auto-generated from Claude conversations. Updated on each session end.")
    lines.append("")
    lines.append(f"**{len(entities)} entities** | **{len(rels)} relationships**")
    lines.append("")
    lines.append("## Entity Summary")
    lines.append("")
    lines.append("| Type | Count | Examples |")
    lines.append("|------|-------|----------|")
    for t in sorted(by_type, key=lambda x: -len(by_type[x])):
        items = by_type[t]
        examples = ", ".join(e["name"] for e in items[:5])
        if len(items) > 5:
            examples += f", +{len(items)-5} more"
        lines.append(f"| {t} | {len(items)} | {examples} |")

    lines.append("")
    lines.append("## Relationship Summary")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|------|-------|")
    for t in sorted(rel_by_type, key=lambda x: -len(rel_by_type[x])):
        lines.append(f"| {t} | {len(rel_by_type[t])} |")

    for t in sorted(by_type, key=lambda x: -len(by_type[x])):
        items = sorted(by_type[t], key=lambda x: x.get("name", ""))
        lines.append("")
        lines.append(f"## {t.title()} ({len(items)})")
        lines.append("")
        lines.append("| Name | Description | First Seen |")
        lines.append("|------|-------------|------------|")
        for e in items:
            lines.append(f"| {e.get('name','')} | {e.get('description','')} | {e.get('date','')} |")

    lines.append("")
    lines.append("## Relationships")
    lines.append("")
    lines.append("| Source | Relationship | Target | Context |")
    lines.append("|--------|-------------|--------|---------|")
    for r in rels:
        ctx = r.get("context", "")
        if len(ctx) > 80:
            ctx = ctx[:77] + "..."
        lines.append(f"| {r.get('source','')} | {r.get('type','')} | {r.get('target','')} | {ctx} |")

    lines.append("")
    lines.append("---")
    lines.append("*Auto-generated by Claude Code knowledge graph extraction hooks.*")
    lines.append("")

    with open(KG_DIR / "README.md", "w") as f:
        f.write("\n".join(lines))

    print(f"Generated README.md: {len(entities)} entities, {len(rels)} relationships")


if __name__ == "__main__":
    main()
